import type { Metadata } from 'next'
import { Abhaya_Libre } from 'next/font/google'
import './globals.css'
import Nav from './nav'

const abhaya_libre = Abhaya_Libre({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={abhaya_libre.className}>
        <div className='flex m-10'>
          <Nav/>
          <div className='mt-[85px]'>
            {children}
          </div>
        </div>
        <div className=' flex bottom-4 text-sm m-10'>
          <p>
            &copy; 2024 Alyssa Zhang. This website was built using Next.js, 
            Typescript, & <a href='https://tailwindcss.com/' className='underline'>Tailwind CSS</a> and is open source.
          </p>
        </div>
      </body>
    </html>
  )
}
