"use client"
import type { Metadata } from 'next'
import { Abhaya_Libre } from 'next/font/google'
import './globals.css'
import Nav from './nav'
import Link from "next/link";
import NavItem from "./NavItem";
import Hamburger from 'hamburger-react'
import { useState } from "react"

const abhaya_libre = Abhaya_Libre({ weight: '400', subsets: ['latin'] })
const pages = [{ title: 'Paintings', link: 'paintings' }, { title: 'Sculptures', link: 'sculptures' }, { title: 'Drawings', link: 'drawings' }, { title: 'Bio', link: 'bio' }, { title: 'Contact', link: 'contact' }]


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isOpen, setIsOpen] = useState(false)
  const handleClick = () => {
    setIsOpen(!isOpen)
  }

  function Hamburglar(isOpen: boolean) {
    if (isOpen) {
      return (
        <div className='w-[273px] text-black text-2xl font-normal mt-10 '>
          {pages.map(page => <NavItem page={page} key={page.link} handleClick={handleClick}/>)}
        </div>
      )
    } else {
      return (
        <div>

        </div>
      )
    }
  }

  return (
    <html lang="en">
      <body className={abhaya_libre.className}>
        <div className="flex flex-row justify-between">
          <h1 className='w-[273px] h-[40px] text-black text-[40px] font-normal ml-10 mt-10'>
            <Link onClick = {handleClick} href={'/'}>Alyssa Zhang</Link>
          </h1>
          <div className="mr-10 mt-10 lg:hidden">
            <Hamburger onToggle={handleClick} />
          </div>
        </div>
        <div className='ml-10'>
          {Hamburglar(isOpen)}
        </div>
        {!isOpen &&
          <div className='flex ml-10'>
            <Nav />
            <div className='mt-[50px] mr-[40px]'>
              {children}
            </div>
          </div>
        }
        <div className=' flex bottom-4 text-sm m-10'>
          <p>
            &copy; 2024 Alyssa Zhang. This website was built using Next.js,
            Typescript, & <a href='https://tailwindcss.com/' className='underline'>Tailwind CSS</a> and is open source.
          </p>
        </div>
      </body>
    </html>
  )
}
